# Generated by Django 4.0.6 on 2022-07-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_at',
            field=models.DateTimeField(null=True),
        ),
    ]
