# Generated by Django 4.0.6 on 2022-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_deadline_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', 'created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
